import Head from 'next/head'
import { Inter } from '@next/font/google'
import Main from 'components/Main'
import Courses from 'components/Courses'
import Lang from 'components/Lang'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <div  >
      <Head>
        <title>The Best</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Main />
<Courses   />

    </div>
  )
}
